version: 2
jobs:
  build:
    docker:
      - image: gliderlabs/ci:build-2
        command: ["/bin/bash"]
    working_directory: /go/src/github.com/gliderlabs/registrator
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: make circleci
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: build
      - deploy:
          name: Deploy website
          command: |
            if is-branch "master"; then
              mv .dockerignore .dockerignore-repo
              eval $(docker run gliderlabs/pagebuilder circleci-cmd)
              mv .dockerignore-repo .dockerignore
            fi
      - deploy:
          name: Deploy beta channel
          command: |
            if is-branch "release"; then
              make release
            fi
