[[constraint]]
  branch = "master"
  name = "github.com/Azure/go-ansiterm"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/Nvveen/Gotty"

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-etcd"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  branch = "master"
  name = "github.com/gliderlabs/pkg"

[[constraint]]
  version = "0.8.1"
  name = "github.com/hashicorp/consul"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-cleanhttp"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "gopkg.in/coreos/go-etcd.v0"
